let saborEmpanada=prompt("sabor de su empanada")
let saborGaseosa=prompt("sabor de su gaseosa")
let nombrePostre=prompt("nombre de su postre")
let cantidadEmpanada=Number(prompt("cuantas empanadas"))
let cantidadGaseosa=Number(prompt("cuantas gaseosas"))
let cantidadPostre=Number(prompt("cuantos postres"))
alert ("su empanada vale : $" + cantidadEmpanada * 3000)
alert ("su gaseosa vale : $" + cantidadGaseosa * 4000)
alert ("su postre vale : $" + cantidadPostre * 8000)
alert